SELECT * FROM TB_PRODUTOS;
SELECT * FROM TB_CLIENTES WHERE ESTADO = 'RJ';
SELECT * FROM TB_PRODUTOS WHERE SABOR = 'Laranja';
SELECT * FROM TB_PRODUTOS WHERE SABOR = 'Limão';
SELECT * FROM TB_PRODUTOS WHERE SABOR = 'Cítricos';

UPDATE TB_PRODUTOS SET SABOR = 'Cítricos' WHERE SABOR = 'Limão';

SELECT * FROM TB_VENDEDORES WHERE NOME = 'Cláudia Morais';