SELECT * FROM TB_CLIENTES;

SELECT * FROM TB_PRODUTOS;

SELECT IDADE, CPF, NOME, DATA_NASCIMENTO FROM TB_CLIENTES;

SELECT CPF AS CPF_DO_CLIENTE, NOME AS NOME_DO_CLIENTE, IDADE, DATA_NASCIMENTO FROM TB_CLIENTES;

