DECLARE
    V_ID CLIENTE.ID%TYPE;
    V_SEGMERCADO_ID SEGMERCADO.ID%TYPE := 1;
    
    CURSOR CUR_CLIENTE IS
        SELECT ID
        FROM CLIENTE;
BEGIN
    OPEN CUR_CLIENTE;
    LOOP
        FETCH CUR_CLIENTE INTO V_ID;
        EXIT WHEN CUR_CLIENTE%NOTFOUND;
        ATUALIZAR_CLI_SEG_MERCADO(V_ID, V_SEGMERCADO_ID);
    END LOOP;
    
    CLOSE CUR_CLIENTE;
    COMMIT;
END;

SELECT * FROM CLIENTE;