DECLARE
    V_SEGMERCADO_ID SEGMERCADO.ID%TYPE := 2;
    CURSOR CUR_CLIENTE IS
        SELECT ID
        FROM CLIENTE;
BEGIN
    FOR CLI_REC IN CUR_CLIENTE LOOP
        ATUALIZAR_CLI_SEG_MERCADO(CLI_REC.ID, V_SEGMERCADO_ID);
    END LOOP;
    COMMIT;
END;

SELECT * FROM CLIENTE;