CREATE OR REPLACE FUNCTION CATEGORIA_CLIENTE
    (P_FATURAMENTO_PREVISTO IN CLIENTE.FATURAMENTO_PREVISTO%TYPE)
    RETURN CLIENTE.CATEGORIA%TYPE
IS
BEGIN
    IF P_FATURAMENTO_PREVISTO < 10000 THEN
        RETURN 'PEQUENO';
        ELSE 
            IF P_FATURAMENTO_PREVISTO < 50000 THEN
            RETURN 'MEDIO';
            ElSE
                IF P_FATURAMENTO_PREVISTO < 100000 THEN
                RETURN 'MEDIO GRANDE';
                ELSE
                    RETURN 'GRANDE';
            END IF;
        END IF;
    END IF;
END;