CREATE OR REPLACE PROCEDURE INCLUIR_SEGMERCADO
    (P_ID IN SEGMERCADO.ID%TYPE, 
    P_DESCRICAO IN SEGMERCADO.DESCRICAO%TYPE)
IS
BEGIN 
    INSERT INTO SEGMERCADO 
        VALUES (P_ID, UPPER(P_DESCRICAO));
    COMMIT;
END;

EXECUTE INCLUIR_SEGMERCADO(3, 'Farmaceutico');

BEGIN
incluir_segmercado(4, 'Industrial');
END;

SELECT * FROM SEGMERCADO;



