CREATE OR REPLACE FUNCTION OBTER_DESCRICAO_SEGMERCADO 
    (P_ID IN SEGMERCADO.ID%TYPE)
    RETURN SEGMERCADO.DESCRICAO%TYPE

IS
    V_DESCRICAO SEGMERCADO.DESCRICAO%TYPE;
BEGIN
    SELECT DESCRICAO INTO V_DESCRICAO
        FROM SEGMERCADO
        WHERE ID = P_ID;
    RETURN V_DESCRICAO;
END;
/*VARIABLE G_DESCRICAO VARCHAR2(100)
EXECUTE :G_DESCRICAO := OBTER_DESCRICAO_SEGMERCADO (3)
PRINT G_DESCRICAO*/


DECLARE
    V_DESCRICAO SEGMERCADO.DESCRICAO%TYPE;
BEGIN
    V_DESCRICAO := OBTER_DESCRICAO_SEGMERCADO(2);
    DBMS_OUTPUT.PUT_LINE('Descrição: '||V_DESCRICAO);
END;
