CREATE OR REPLACE PROCEDURE INCLUIR_CLIENTE
    (P_ID IN CLIENTE.ID%TYPE,
    P_RAZAO_SOCIAL IN CLIENTE.RAZAO_SOCIAL%TYPE,
    P_CNPJ IN CLIENTE.CNPJ%TYPE,
    P_SEGMERCADO_ID IN CLIENTE.SEGMERCADO_ID%TYPE,
    P_FATURAMENTO_PREVISTO IN CLIENTE.FATURAMENTO_PREVISTO%TYPE)
    
IS
    V_CATEGORIA CLIENTE.CATEGORIA%TYPE;
BEGIN
    V_CATEGORIA := CATEGORIA_CLIENTE(P_FATURAMENTO_PREVISTO);
    
    INSERT INTO CLIENTE
        VALUES (P_ID, UPPER(P_RAZAO_SOCIAL), P_CNPJ, P_SEGMERCADO_ID, SYSDATE, P_FATURAMENTO_PREVISTO,V_CATEGORIA);
    COMMIT;
END;
